### ISSUE TITLE
Performance testing orchestration tools

### ISSUE THREAD

**Issue by chrisvdg** [zero-os/0-stor#381]
As part of #296 we need Python tools to do the following:

* deploy and start both client and server on different systems (packet.net, G8 servers, local setup)
* define where the server's storage and lsm tree is running (SSD, HDD, memory)
* run the benchmarks
* retrieve the results from these benchmarks and plot them into graphs (e.g. Matplotlib)

**Comment by zaibon** [comment]
@katia-e I tried to run the orchestrator with the [default configuration](https://github.com/zero-os/0-stor/blob/benchmark_orchestrator/benchmark/orchestrator/orchConfig.yaml)

But got this error:
```
Traceback (most recent call last):
  File "orchestrator.py", line 103, in <module>
    main(sys.argv[1:])    
  File "orchestrator.py", line 95, in main
    report.add_timeplot()
  File "/home/zaibon/dev/go/src/github.com/zero-os/0-stor/benchmark/orchestrator/lib/report.py", line 278, in add_timeplot
    files = self.__plot_per_interval__()
  File "/home/zaibon/dev/go/src/github.com/zero-os/0-stor/benchmark/orchestrator/lib/report.py", line 329, in __plot_per_interval__
    plt.plot(time_line, per_interval[len(per_interval)-len(time_line):],'bo--', label=self.timeplots_added)
  File "/home/zaibon/.virtualenvs/global/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3261, in plot
    ret = ax.plot(*args, **kwargs)
  File "/home/zaibon/.virtualenvs/global/lib/python3.6/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/home/zaibon/.virtualenvs/global/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1372, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/home/zaibon/.virtualenvs/global/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 404, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "/home/zaibon/.virtualenvs/global/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 384, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/home/zaibon/.virtualenvs/global/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 243, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (13,) and (2,)
(global) 
```

**Comment by GlenDC** [comment]
> But got this error:

I think they fixed this by now in the PR branches. @chrisvdg and/or @katia-e, can you please confirm?

**Comment by chrisvdg** [comment]
@GlenDC, it's a pretty old comment and I've never seen this error while testing, so pretty sure it's fixed

**Comment by katia-e** [comment]
@GlenDC , yes it was fixed then

**Comment by zaibon** [comment]
closing, thanks @katia-e
